/**
 * STACKLY - Complete 32-Product Pharmacy & Healthcare Catalog
 * 8 Categories with 4 Unique Products each.
 */

const PRODUCTS = [
    // -------------------------------------------------------------------------
    // 1. OTC MEDICINES (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-med-1",
        name: "Paracetamol Extra 500mg",
        category: "medicines",
        categoryName: "OTC Medicines",
        price: 8.49,
        originalPrice: 10.99,
        discountPercent: 22,
        rating: 4.8,
        reviewsCount: 94,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/01_paracetamol_extra_500mg.webp",
        shortDescription: "Fast-acting pain relief for headaches, fever, toothaches, and muscular body aches.",
        description: "Formulated with 500mg pure paracetamol for rapid absorption and long-lasting fever reduction.",
        benefits: ["Relieves mild to moderate pain", "Reduces high body temperature", "Gentle on stomach lining", "Rapid onset within 20 minutes"],
        usage: "Adults: 1 to 2 tablets every 4 to 6 hours as needed. Do not exceed 8 tablets in 24 hours.",
        specifications: { "Form": "Tablets", "Strength": "500mg", "Pack Size": "24 Tablets", "Age": "12+ Years" }
    },
    {
        id: "prod-med-2",
        name: "Ibuprofen Fast Relief 400mg",
        category: "medicines",
        categoryName: "OTC Medicines",
        price: 9.99,
        originalPrice: 12.99,
        discountPercent: 23,
        rating: 4.7,
        reviewsCount: 82,
        inStock: true,
        isFeatured: true,
        isPopular: false,
        image: "assets/images/02_ibuprofen_fast_relief_400mg.webp",
        shortDescription: "Targeted anti-inflammatory relief for joint stiffness, backache, and toothache.",
        description: "Coated 400mg liquid-gel capsules for quick reduction of painful joint and muscle inflammation.",
        benefits: ["Reduces tissue inflammation", "Targeted joint & muscular relief", "Liquid-gel rapid absorption"],
        usage: "Take 1 capsule with food every 6 to 8 hours as required.",
        specifications: { "Form": "Softgels", "Strength": "400mg", "Pack Size": "20 Softgels" }
    },
    {
        id: "prod-med-3",
        name: "Cough & Cold Night Syrup 200ml",
        category: "medicines",
        categoryName: "OTC Medicines",
        price: 11.49,
        originalPrice: 14.99,
        discountPercent: 23,
        rating: 4.9,
        reviewsCount: 115,
        inStock: true,
        isFeatured: false,
        isPopular: true,
        image: "assets/images/41_cough_cold_night_syrup_200ml.webp",
        shortDescription: "Soothing nighttime decongestant formula to calm dry coughs and clear nasal passages.",
        description: "Triple-action soothing syrup that relieves chest congestion, nasal tickles, and promotes restful sleep.",
        benefits: ["Calms nagging night cough", "Clears blocked nasal airways", "Soothes irritated throat tissue"],
        usage: "Adults take 10ml at bedtime using measuring cap included.",
        specifications: { "Volume": "200ml", "Flavor": "Cherry Honey", "Age": "12+ Years" }
    },
    {
        id: "prod-med-4",
        name: "Antacid Extra Relief Chewables",
        category: "medicines",
        categoryName: "OTC Medicines",
        price: 7.99,
        originalPrice: 9.99,
        discountPercent: 20,
        rating: 4.6,
        reviewsCount: 63,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/40_antacid_extra_relief_chewables.webp",
        shortDescription: "Instant neutralization of acid reflux, heartburn, and sour stomach indigestion.",
        description: "Dual Calcium Carbonate & Magnesium Hydroxide formula for fast relief from burning acid sensations.",
        benefits: ["Neutralizes stomach acid in seconds", "Smooth peppermint flavor", "Non-constipating formula"],
        usage: "Chew 2 tablets thoroughly when symptoms occur.",
        specifications: { "Form": "Chewable Tablets", "Count": "48 Tablets", "Flavor": "Peppermint" }
    },

    // -------------------------------------------------------------------------
    // 2. VITAMINS & SUPPLEMENTS (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-vit-1",
        name: "Liposomal Vitamin C 1000mg",
        category: "vitamins",
        categoryName: "Vitamins & Supplements",
        price: 24.99,
        originalPrice: 32.99,
        discountPercent: 24,
        rating: 4.9,
        reviewsCount: 128,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/03_liposomal_vitamin_c_1000mg.webp",
        shortDescription: "High-absorption liposomal vitamin C for immune system defense and collagen synthesis.",
        description: "Liposomal Vitamin C uses advanced phospholipid technology to deliver maximum ascorbic acid directly into your cells without stomach discomfort.",
        benefits: ["Supports white blood cell function", "Enhances collagen synthesis", "Powerful antioxidant defense", "Gentle on sensitive stomachs"],
        usage: "Take 2 capsules daily with water during a meal.",
        specifications: { "Form": "Capsules", "Serving Size": "2 Capsules", "Count": "60 Capsules", "Gluten-Free": "Yes" }
    },
    {
        id: "prod-vit-2",
        name: "Vitamin D3 5000 IU Softgels",
        category: "vitamins",
        categoryName: "Vitamins & Supplements",
        price: 16.99,
        originalPrice: 21.99,
        discountPercent: 22,
        rating: 4.9,
        reviewsCount: 154,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/04_vitamin_d3_5000_iu_softgels.webp",
        shortDescription: "Essential sunshine vitamin in organic cold-pressed olive oil for bone & immune resilience.",
        description: "High-potency Cholecalciferol (D3) suspended in organic extra virgin olive oil for maximum bio-availability.",
        benefits: ["Strengthens bone density", "Boosts seasonal immune mood", "High potency 5000 IU dose"],
        usage: "Take 1 softgel daily with a fat-containing meal.",
        specifications: { "Form": "Softgels", "Potency": "5000 IU", "Count": "120 Softgels" }
    },
    {
        id: "prod-vit-3",
        name: "Zinc Picolinate 50mg",
        category: "vitamins",
        categoryName: "Vitamins & Supplements",
        price: 14.99,
        originalPrice: 18.99,
        discountPercent: 21,
        rating: 4.8,
        reviewsCount: 88,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/37_zinc_picolinate_50mg.webp",
        shortDescription: "High-potency chelated zinc for cellular immunity and skin clarity support.",
        description: "Zinc Picolinate offers superior bio-availability compared to standard zinc oxide for optimal cell defense.",
        benefits: ["Supports immune enzyme function", "Promotes skin healing", "High absorption chelate"],
        usage: "Take 1 tablet daily with food.",
        specifications: { "Form": "Tablets", "Strength": "50mg", "Count": "100 Tablets" }
    },
    {
        id: "prod-vit-4",
        name: "Omega-3 Wild Fish Oil 1200mg",
        category: "vitamins",
        categoryName: "Vitamins & Supplements",
        price: 22.99,
        originalPrice: 28.99,
        discountPercent: 20,
        rating: 4.9,
        reviewsCount: 176,
        inStock: true,
        isFeatured: false,
        isPopular: true,
        image: "assets/images/01_omega_3_wild_fish_oil_1200mg.webp",
        shortDescription: "Molecularly distilled fish oil rich in EPA & DHA for heart and joint mobility.",
        description: "Purified wild-caught triglyceride omega-3 softgels with natural lemon flavor to eliminate fishy burps.",
        benefits: ["Supports cardiovascular health", "Promotes joint flexibility", "Zero fishy aftertaste"],
        usage: "Take 2 softgels daily with lunch or dinner.",
        specifications: { "Form": "Softgels", "EPA/DHA": "800mg/400mg", "Count": "90 Softgels" }
    },

    // -------------------------------------------------------------------------
    // 3. SKIN CARE (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-skin-1",
        name: "Hyaluronic Acid Hydrating Serum",
        category: "skin-care",
        categoryName: "Skin Care",
        price: 18.99,
        originalPrice: 24.99,
        discountPercent: 24,
        rating: 4.7,
        reviewsCount: 76,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/05_hyaluronic_acid_hydrating_serum.webp",
        shortDescription: "Deeply moisturizing serum with multi-molecular hyaluronic acid and pro-vitamin B5.",
        description: "Replenishes skin moisture barrier, plumps fine dehydration lines, and enhances natural skin radiance.",
        benefits: ["Multi-layer deep hydration", "Plumps skin texture", "Oil-free fragrance-free formula"],
        usage: "Apply 3-4 drops morning and night onto clean, damp skin.",
        specifications: { "Volume": "30ml", "Skin Type": "All Types", "Paraben-Free": "Yes" }
    },
    {
        id: "prod-skin-2",
        name: "Ceramide Moisture Lock Cream",
        category: "skin-care",
        categoryName: "Skin Care",
        price: 21.99,
        originalPrice: 27.99,
        discountPercent: 21,
        rating: 4.8,
        reviewsCount: 92,
        inStock: true,
        isFeatured: true,
        isPopular: false,
        image: "assets/images/06_ceramide_moisture_lock_cream.webp",
        shortDescription: "Rich dermatological barrier repair cream with 3 essential ceramides and niacinamide.",
        description: "Restores compromised skin barriers damaged by climate dryness, tretinoin, or aggressive cleansers.",
        benefits: ["Restores damaged lipid barrier", "Non-greasy 24h moisture seal", "Dermatologist approved"],
        usage: "Smooth liberally onto face and neck after cleansing.",
        specifications: { "Volume": "100g", "Ceramides": "1, 3, 6-II", "Non-Comedogenic": "Yes" }
    },
    {
        id: "prod-skin-3",
        name: "Mineral Broad-Spectrum Sunscreen SPF 50+",
        category: "skin-care",
        categoryName: "Skin Care",
        price: 19.99,
        originalPrice: 25.99,
        discountPercent: 23,
        rating: 4.9,
        reviewsCount: 140,
        inStock: true,
        isFeatured: false,
        isPopular: true,
        image: "assets/images/34_mineral_broad_spectrum_sunscreen_spf_50.webp",
        shortDescription: "100% Zinc Oxide invisible mineral sunblock protecting against UVA/UVB photo-aging.",
        description: "Ultra-lightweight physical sun protection that absorbs cleanly without white cast or pore clogging.",
        benefits: ["Broad-Spectrum SPF 50+ UVA/UVB", "Zero white cast finish", "Reef-safe non-nano zinc"],
        usage: "Apply evenly 15 minutes before sun exposure. Reapply every 2 hours.",
        specifications: { "Volume": "75ml", "SPF": "50+", "Active": "Zinc Oxide 18%" }
    },
    {
        id: "prod-skin-4",
        name: "Gentle Retinol Night Renewal Serum",
        category: "skin-care",
        categoryName: "Skin Care",
        price: 26.99,
        originalPrice: 34.99,
        discountPercent: 23,
        rating: 4.8,
        reviewsCount: 68,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/35_gentle_retinol_night_renewal_serum.webp",
        shortDescription: "Micro-encapsulated 0.3% retinol serum promoting cellular turnover and smooth texture.",
        description: "Time-release encapsulation minimizes peeling while smoothing fine lines, dark spots, and texture.",
        benefits: ["Accelerates cell renewal", "Fades dark sun spots", "Time-release gentle delivery"],
        usage: "Apply 2-3 drops at night twice weekly, gradually increasing to nightly.",
        specifications: { "Volume": "30ml", "Retinol": "0.3% Encapsulated", "Night Use": "Yes" }
    },

    // -------------------------------------------------------------------------
    // 4. MEDICAL DEVICES (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-dev-1",
        name: "Digital Pulse Oximeter",
        category: "medical-devices",
        categoryName: "Medical Devices",
        price: 29.99,
        originalPrice: 39.99,
        discountPercent: 25,
        rating: 4.9,
        reviewsCount: 210,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/07_digital_pulse_oximeter.webp",
        shortDescription: "Accurate fingertip oxygen saturation (SpO2) and pulse rate monitor with OLED display.",
        description: "Medical-grade optical sensor provides instantaneous reading of arterial blood oxygen and heart rate.",
        benefits: ["Fast 5-second reading", "High-definition dual color OLED", "Auto power-off battery saver"],
        usage: "Place finger inside chamber, press power button, and stay still for 5 seconds.",
        specifications: { "Display": "OLED Dual Color", "SpO2 Range": "70%-100%", "Power": "2x AAA Batteries" }
    },
    {
        id: "prod-dev-2",
        name: "Automatic Upper Arm BP Monitor",
        category: "medical-devices",
        categoryName: "Medical Devices",
        price: 44.99,
        originalPrice: 59.99,
        discountPercent: 25,
        rating: 4.9,
        reviewsCount: 185,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/08_automatic_upper_arm_bp_monitor.webp",
        shortDescription: "Clinical accuracy blood pressure monitor with irregular heartbeat detector & dual user memory.",
        description: "One-touch automatic inflation cuff with WHO hypertension classification indicator and 2x90 reading memory.",
        benefits: ["One-touch automatic reading", "Irregular heartbeat indicator", "2x90 dual memory tracking"],
        usage: "Wrap cuff 1 inch above elbow at heart level, rest 5 mins, press START.",
        specifications: { "Cuff Size": "22-42cm Universal", "Memory": "180 Total Logs", "Display": "Backlit LCD" }
    },
    {
        id: "prod-dev-3",
        name: "Infrared Non-Contact Forehead Thermometer",
        category: "medical-devices",
        categoryName: "Medical Devices",
        price: 32.99,
        originalPrice: 42.99,
        discountPercent: 23,
        rating: 4.8,
        reviewsCount: 130,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/29_infrared_non_contact_forehead_thermometer.webp",
        shortDescription: "1-second hygienic touchless temperature scanner with color fever warning light.",
        description: "High-precision infrared sensor measures forehead temperature from 1-3cm distance silently.",
        benefits: ["Hygienic touchless measurement", "Instant 1-second result", "Color-coded fever alert"],
        usage: "Point scanner 1-3cm from center of forehead and pull trigger.",
        specifications: { "Distance": "1-3cm", "Speed": "1 Second", "Memory": "32 Readings" }
    },
    {
        id: "prod-dev-4",
        name: "Portable Ultrasonic Mesh Nebulizer",
        category: "medical-devices",
        categoryName: "Medical Devices",
        price: 39.99,
        originalPrice: 49.99,
        discountPercent: 20,
        rating: 4.9,
        reviewsCount: 96,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/28_portable_ultrasonic_mesh_nebulizer.webp",
        shortDescription: "Whisper-quiet pocket inhaler for asthma, bronchitis, and respiratory treatments.",
        description: "Vibrating mesh technology produces ultra-fine micro mist particles (<5μm) for rapid lung absorption.",
        benefits: ["Ultra-fine <5μm aerosol mist", "Whisper-quiet operation", "USB rechargeable & portable"],
        usage: "Fill medication cup, attach mask or mouthpiece, press power button.",
        specifications: { "Particle Size": "<5μm", "Weight": "100g", "Power": "USB / 2x AA" }
    },

    // -------------------------------------------------------------------------
    // 5. BABY CARE (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-baby-1",
        name: "Organic Gentle Baby Lotion 250ml",
        category: "baby-care",
        categoryName: "Baby Care",
        price: 12.99,
        originalPrice: 15.99,
        discountPercent: 18,
        rating: 4.9,
        reviewsCount: 52,
        inStock: true,
        isFeatured: true,
        isPopular: false,
        image: "assets/images/24_organic_gentle_baby_lotion_250ml.webp",
        shortDescription: "Hypoallergenic nourishing lotion with organic chamomile and oat kernel extracts.",
        description: "Pediatrician-tested formula locks in essential moisture to protect delicate infant skin from chafing.",
        benefits: ["Pediatrician dermatologically tested", "pH balanced for newborn skin", "Calming chamomile fragrance"],
        usage: "Smooth gently over baby's skin after warm bath time.",
        specifications: { "Volume": "250ml", "Hypoallergenic": "Yes", "Pediatrician Approved": "Yes" }
    },
    {
        id: "prod-baby-2",
        name: "Tear-Free Infant Shampoo & Wash",
        category: "baby-care",
        categoryName: "Baby Care",
        price: 10.99,
        originalPrice: 13.99,
        discountPercent: 21,
        rating: 4.8,
        reviewsCount: 74,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/25_tear_free_infant_shampoo_wash.webp",
        shortDescription: "Ultra-mild head-to-toe cleanser that leaves baby's hair soft and skin hydrated.",
        description: "Soap-free, tear-free formulation enriched with organic calendula flower extract.",
        benefits: ["100% Tear-free certified", "No parabens or sulfates", "Gentle calendula soothing"],
        usage: "Pump onto hands or soft washcloth and cleanse hair and body gently.",
        specifications: { "Volume": "300ml", "Tear-Free": "Yes", "Paraben-Free": "Yes" }
    },
    {
        id: "prod-baby-3",
        name: "Diaper Rash Barrier Cream 100g",
        category: "baby-care",
        categoryName: "Baby Care",
        price: 8.99,
        originalPrice: 11.99,
        discountPercent: 25,
        rating: 4.9,
        reviewsCount: 110,
        inStock: true,
        isFeatured: false,
        isPopular: true,
        image: "assets/images/26_diaper_rash_barrier_cream_100g.webp",
        shortDescription: "Fast-acting 40% Zinc Oxide paste soothing inflammation and preventing diaper wetness.",
        description: "Creates an immediate protective barrier over irritated skin, relieving redness from first application.",
        benefits: ["40% Max Strength Zinc Oxide", "Immediate moisture barrier", "Relieves diaper redness fast"],
        usage: "Apply thick layer onto clean, dry diaper area at every diaper change.",
        specifications: { "Weight": "100g", "Zinc Oxide": "40%", "Pediatrician Formulated": "Yes" }
    },
    {
        id: "prod-baby-4",
        name: "99% Pure Water Baby Wipes (80s)",
        category: "baby-care",
        categoryName: "Baby Care",
        price: 5.99,
        originalPrice: 7.99,
        discountPercent: 25,
        rating: 4.9,
        reviewsCount: 160,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/27_99_pure_water_baby_wipes_80s.webp",
        shortDescription: "Ultra-soft un-fragranced wet wipes made with 99% purified water and aloe leaf juice.",
        description: "Thick textured cloth wipes engineered for sensitive newborn skin with zero alcohol or harsh fragrances.",
        benefits: ["99% Purified water formulation", "0% Alcohol & Fragrance", "Extra thick plant-based cloth"],
        usage: "Pull single wipe from pop-up lid to cleanse hands, face, or diaper area.",
        specifications: { "Count": "80 Wipes", "Water": "99%", "Biodegradable": "Yes" }
    },

    // -------------------------------------------------------------------------
    // 6. PERSONAL CARE (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-pers-1",
        name: "Antimicrobial Body Wash 500ml",
        category: "personal-care",
        categoryName: "Personal Care",
        price: 9.99,
        originalPrice: 12.99,
        discountPercent: 23,
        rating: 4.6,
        reviewsCount: 44,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/23_antimicrobial_body_wash_500ml.webp",
        shortDescription: "Gentle antiseptic cleansing wash eliminating 99.9% of harmful surface bacteria.",
        description: "Formulated with moisturizing aloe vera and tea tree extract to cleanse deeply without drying skin.",
        benefits: ["Kills 99.9% body bacteria", "Enriched with aloe vera", "Dermatologically tested"],
        usage: "Lather onto wet skin during daily shower or bath.",
        specifications: { "Volume": "500ml", "Antimicrobial": "Yes", "Skin Type": "All Types" }
    },
    {
        id: "prod-pers-2",
        name: "Herbal Toothpaste & Gum Protect",
        category: "personal-care",
        categoryName: "Personal Care",
        price: 6.49,
        originalPrice: 8.49,
        discountPercent: 23,
        rating: 4.8,
        reviewsCount: 89,
        inStock: true,
        isFeatured: true,
        isPopular: false,
        image: "assets/images/22_herbal_toothpaste_gum_protect.webp",
        shortDescription: "Enamel safe herbal fluoride paste with clove, neem, and peppermint for 12h fresh breath.",
        description: "Clinically proven botanical toothpaste that reduces plaque build-up and soothes bleeding gums.",
        benefits: ["Reduces gum bleeding & plaque", "Enamel-safe fluoride protection", "12h long fresh breath"],
        usage: "Brush thoroughly twice daily after meals.",
        specifications: { "Weight": "120g", "Fluoride": "Yes", "SLS-Free": "Yes" }
    },
    {
        id: "prod-pers-3",
        name: "Gentle Antiseptic Hand Wash 300ml",
        category: "personal-care",
        categoryName: "Personal Care",
        price: 4.99,
        originalPrice: 6.49,
        discountPercent: 23,
        rating: 4.7,
        reviewsCount: 56,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/21_gentle_antiseptic_hand_wash_300ml.webp",
        shortDescription: "Moisturizing liquid hand soap with antibacterial chlorhexidine and vitamin E.",
        description: "Frequent-use hand wash designed for healthcare settings and home hand hygiene without drying skin.",
        benefits: ["Kills 99.99% germs", "Vitamin E skin conditioners", "Frequent-use gentle formula"],
        usage: "Pump onto wet hands, lather for 20 seconds, rinse thoroughly.",
        specifications: { "Volume": "300ml", "Pump": "Yes", "Moisturizing": "Yes" }
    },
    {
        id: "prod-pers-4",
        name: "Natural Deodorant Roll-On 75ml",
        category: "personal-care",
        categoryName: "Personal Care",
        price: 7.99,
        originalPrice: 9.99,
        discountPercent: 20,
        rating: 4.8,
        reviewsCount: 71,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/20_natural_deodorant_roll_on_75ml.webp",
        shortDescription: "Aluminum-free 24-hour odor protection with zinc ricinoleate and natural coconut oil.",
        description: "Glides on clear without staining clothes while neutralizing odor-causing underarm bacteria naturally.",
        benefits: ["0% Aluminum & Parabens", "24-Hour odor neutralization", "Non-staining clear formula"],
        usage: "Apply 2-3 swipes onto clean dry underarms.",
        specifications: { "Volume": "75ml", "Aluminum-Free": "Yes", "Gender": "Unisex" }
    },

    // -------------------------------------------------------------------------
    // 7. HEALTH & WELLNESS (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-well-1",
        name: "Organic Ashwagandha KSM-66 600mg",
        category: "wellness",
        categoryName: "Health & Wellness",
        price: 19.99,
        originalPrice: 25.99,
        discountPercent: 23,
        rating: 4.9,
        reviewsCount: 142,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/16_organic_ashwagandha_ksm_66_600mg.webp",
        shortDescription: "Full-spectrum root extract adaptogen for cortisol stress control and mental focus.",
        description: "KSM-66 Ashwagandha is clinically evaluated to reduce physiological stress markers and enhance stamina.",
        benefits: ["Lowers cortisol stress levels", "Enhances mental clarity & calm", "Supports healthy stamina"],
        usage: "Take 1 capsule twice daily with food.",
        specifications: { "Form": "Capsules", "Extract": "KSM-66 600mg", "Count": "60 Veg Capsules" }
    },
    {
        id: "prod-well-2",
        name: "Melatonin Sleep Support Gummies 5mg",
        category: "wellness",
        categoryName: "Health & Wellness",
        price: 15.99,
        originalPrice: 19.99,
        discountPercent: 20,
        rating: 4.8,
        reviewsCount: 118,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/17_melatonin_sleep_support_gummies_5mg.webp",
        shortDescription: "Delicious blackberry gummies infused with 5mg Melatonin, L-Theanine & Chamomile.",
        description: "Helps reset circadian sleep cycles, allowing you to fall asleep faster and wake refreshed without grogginess.",
        benefits: ["Fall asleep 30% faster", "Non-habit forming formula", "Pectin-based vegan gummy"],
        usage: "Chew 2 gummies 30 minutes before bedtime.",
        specifications: { "Form": "Gummies", "Melatonin": "5mg", "Count": "60 Gummies", "Flavor": "Blackberry" }
    },
    {
        id: "prod-well-3",
        name: "Electrolyte Hydration Powder Packets",
        category: "wellness",
        categoryName: "Health & Wellness",
        price: 17.99,
        originalPrice: 22.99,
        discountPercent: 21,
        rating: 4.9,
        reviewsCount: 95,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/18_electrolyte_hydration_powder_packets.webp",
        shortDescription: "Rapid cellular hydration mix with sodium, potassium, magnesium, and vitamin C.",
        description: "Calculated osmolality balance that delivers water & vital minerals into bloodstream 2x faster than water alone.",
        benefits: ["2x Faster hydration than water", "No artificial sweeteners", "Pouch travel stick packs"],
        usage: "Mix 1 stick pack into 500ml cold water.",
        specifications: { "Pack Count": "16 Sticks", "Flavor": "Lemon Lime", "Sugar": "Zero Added" }
    },
    {
        id: "prod-well-4",
        name: "Probiotic Gut Flora 50 Billion CFU",
        category: "wellness",
        categoryName: "Health & Wellness",
        price: 27.99,
        originalPrice: 35.99,
        discountPercent: 22,
        rating: 4.9,
        reviewsCount: 164,
        inStock: true,
        isFeatured: false,
        isPopular: true,
        image: "assets/images/19_probiotic_gut_flora_50_billion_cfu.webp",
        shortDescription: "10-strain delayed-release probiotic culture for digestive balance and bloating relief.",
        description: "Acid-resistant capsules ensure 50 billion active live cultures reach the intestinal gut intact.",
        benefits: ["Relieves bloating & indigestion", "Supports healthy gut microbiome", "Delayed-release stomach acid protection"],
        usage: "Take 1 capsule daily on an empty stomach.",
        specifications: { "CFU": "50 Billion", "Strains": "10 Clinically Studied", "Count": "30 Capsules" }
    },

    // -------------------------------------------------------------------------
    // 8. FIRST AID & EMERGENCY (4 Products)
    // -------------------------------------------------------------------------
    {
        id: "prod-aid-1",
        name: "Compact First Aid Kit (50 Piece)",
        category: "first-aid",
        categoryName: "First Aid & Emergency",
        price: 15.99,
        originalPrice: 19.99,
        discountPercent: 20,
        rating: 4.8,
        reviewsCount: 165,
        inStock: true,
        isFeatured: true,
        isPopular: true,
        image: "assets/images/15_compact_first_aid_kit_50_piece.webp",
        shortDescription: "All-in-one emergency kit containing sterile bandages, antiseptic wipes, scissors, and tweezers.",
        description: "Compact water-resistant hard case designed for home, automobile, travel, and outdoor emergency response.",
        benefits: ["50 medical items included", "Water-resistant EVA hard case", "Lightweight portable design"],
        usage: "Keep accessible in home or vehicle. Use sterile supplies for minor cuts and scrapes.",
        specifications: { "Pieces": "50 Items", "Case": "EVA Hard Shell", "Weight": "220g" }
    },
    {
        id: "prod-aid-2",
        name: "Waterproof Hydrocolloid Bandages (20s)",
        category: "first-aid",
        categoryName: "First Aid & Emergency",
        price: 7.99,
        originalPrice: 9.99,
        discountPercent: 20,
        rating: 4.9,
        reviewsCount: 88,
        inStock: true,
        isFeatured: true,
        isPopular: false,
        image: "assets/images/14_waterproof_hydrocolloid_bandages_20s.webp",
        shortDescription: "Moisture-sealing hydrocolloid blister plasters accelerating wound healing 2x faster.",
        description: "Creates a gel cushion over blisters and minor wounds that seals out dirt, bacteria, and water.",
        benefits: ["Heals blisters 2x faster", "100% Waterproof stay-on seal", "Discreet clear cushion"],
        usage: "Apply onto clean, dry skin directly over blister or scrape.",
        specifications: { "Count": "20 Assorted Plasters", "Hydrocolloid": "100%", "Waterproof": "Yes" }
    },
    {
        id: "prod-aid-3",
        name: "Antiseptic Wound Cleansing Spray 100ml",
        category: "first-aid",
        categoryName: "First Aid & Emergency",
        price: 6.99,
        originalPrice: 8.99,
        discountPercent: 22,
        rating: 4.7,
        reviewsCount: 52,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/13_antiseptic_wound_cleansing_spray_100ml.webp",
        shortDescription: "Sting-free antiseptic spray for immediate cleansing and infection prevention on minor cuts.",
        description: "Gentle pain-free cleansing solution containing Benzalkonium Chloride that flushes debris out of open skin.",
        benefits: ["No-sting painless application", "Prevents skin infection", "Easy mist pump action"],
        usage: "Spray directly onto affected skin from 5-10cm distance before bandaging.",
        specifications: { "Volume": "100ml", "Sting-Free": "Yes", "Active": "Benzalkonium Chloride" }
    },
    {
        id: "prod-aid-4",
        name: "Burn Relief Gel with Organic Aloe Vera",
        category: "first-aid",
        categoryName: "First Aid & Emergency",
        price: 8.49,
        originalPrice: 10.99,
        discountPercent: 23,
        rating: 4.8,
        reviewsCount: 79,
        inStock: true,
        isFeatured: false,
        isPopular: false,
        image: "assets/images/12_burn_relief_gel_with_organic_aloe_vera.webp",
        shortDescription: "Instant cooling gel with 1% Lidocaine and 98% pure aloe vera for minor burns & sunburn.",
        description: "Rapidly draws heat out of minor household kitchen burns or sunburns while hydrating skin.",
        benefits: ["Instant cooling heat relief", "1% Pain-relieving Lidocaine", "Restores damaged skin moisture"],
        usage: "Apply generous layer over burn area without rubbing.",
        specifications: { "Volume": "120g", "Active": "Lidocaine 1%", "Aloe Vera": "98%" }
    }
];

// Helper to retrieve single product by ID
function getProductById(id) {
    return PRODUCTS.find(p => p.id === id) || null;
}

// Helper to filter products
function searchProducts(searchQuery = '', category = 'all', sortBy = 'default', maxPrice = 100, minRating = 0) {
    if (typeof searchQuery === 'object' && searchQuery !== null) {
        // Handle destructured object parameter if passed
        const opts = searchQuery;
        category = opts.category || 'all';
        searchQuery = opts.searchQuery || '';
        maxPrice = opts.maxPrice || 100;
        minRating = opts.minRating || 0;
        sortBy = opts.sortBy || 'default';
    }

    let list = PRODUCTS.filter(p => {
        const matchesCategory = (category === 'all' || p.category === category);
        const matchesSearch = !searchQuery || p.name.toLowerCase().includes(searchQuery.toLowerCase()) || p.shortDescription.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesPrice = p.price <= maxPrice;
        const matchesRating = p.rating >= minRating;
        return matchesCategory && matchesSearch && matchesPrice && matchesRating;
    });

    if (sortBy === 'price-low') list.sort((a, b) => a.price - b.price);
    if (sortBy === 'price-high') list.sort((a, b) => b.price - a.price);
    if (sortBy === 'rating') list.sort((a, b) => b.rating - a.rating);
    if (sortBy === 'newest') list.sort((a, b) => b.reviewsCount - a.reviewsCount);

    return list;
}
